# Generated by Django 3.2.4 on 2023-11-19 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(blank=True, max_length=255, null=True)),
                ('uid', models.CharField(max_length=255, null=True)),
                ('full_name', models.CharField(max_length=255, null=True)),
                ('profile_image', models.CharField(max_length=255, null=True)),
                ('call_type', models.CharField(max_length=255, null=True)),
                ('muted', models.BooleanField()),
                ('video_disabled', models.BooleanField()),
                ('datetime', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LiveStreaming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomname', models.CharField(blank=True, max_length=255, null=True)),
                ('isLive', models.BooleanField(default=True)),
                ('isBlocked', models.BooleanField(default=False, null=True)),
                ('priority', models.IntegerField(default=0)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StreamComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomname', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.CharField(max_length=255, null=True)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_datetime', models.DateTimeField(blank=True, null=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ActiveCalls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active_calls', models.ManyToManyField(blank=True, db_constraint=False, related_name='active_calls', to='livestream.ActiveCall')),
                ('room', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='livestream.livestreaming')),
            ],
        ),
    ]
