# Generated by Django 3.2.4 on 2023-04-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestream', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestreaming',
            name='isLive',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
