# Generated by Django 3.2.4 on 2023-04-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestream', '0002_alter_livestreaming_islive'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestreaming',
            name='isBlocked',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='livestreaming',
            name='isLive',
            field=models.BooleanField(default=True),
        ),
    ]
