# Generated by Django 3.2.4 on 2023-04-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestream', '0003_auto_20230416_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestreaming',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livestreaming',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
