# Generated by Django 3.2.4 on 2023-04-19 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livestream', '0004_auto_20230419_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='activecalls',
            name='room',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='livestream.livestreaming'),
        ),
        migrations.AlterField(
            model_name='activecalls',
            name='active_calls',
            field=models.ManyToManyField(blank=True, db_constraint=False, related_name='active_calls', to='livestream.ActiveCall'),
        ),
    ]
