# Generated by Django 3.2 on 2022-09-16 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='thanaungkyow@gmail.com', max_length=250),
            preserve_default=False,
        ),
    ]
