# Generated by Django 3.2.4 on 2023-05-03 19:09

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_userassets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userassets',
            name='animation_image',
            field=models.ImageField(blank=True, null=True, upload_to=profiles.models.profile_image_asset_path),
        ),
    ]
