# Generated by Django 3.2.4 on 2023-05-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_alter_userassets_animation_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userassets',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
