# Generated by Django 3.2.4 on 2023-05-04 07:31

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_alter_profile_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('level', models.CharField(blank=True, max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('animation_image', models.ImageField(blank=True, null=True, upload_to=profiles.models.profile_image_asset_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
