# Generated by Django 3.2.4 on 2023-05-04 07:31

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_assets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='animation_image',
            field=models.ImageField(blank=True, null=True, upload_to=profiles.models.profile_asset_path),
        ),
    ]
