# Generated by Django 3.2 on 2022-10-01 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositrequest',
            name='feedback',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
