# Generated by Django 3.2 on 2022-10-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0003_withdrawrequest_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawrequest',
            name='received_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
