# Generated by Django 3.2 on 2022-10-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0004_withdrawrequest_received_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositrequest',
            name='update_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='withdrawrequest',
            name='update_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
