# Generated by Django 3.2 on 2022-10-02 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0005_auto_20221003_0033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depositrequest',
            old_name='update_datetime',
            new_name='updated_datetime',
        ),
        migrations.RenameField(
            model_name='withdrawrequest',
            old_name='update_datetime',
            new_name='updated_datetime',
        ),
    ]
