# Generated by Django 3.2.4 on 2022-10-03 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0006_auto_20221003_0048'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarnMinuteExchanger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_minute_rate', models.DecimalField(decimal_places=2, default=0.2, max_digits=8)),
            ],
            options={
                'verbose_name_plural': "Earn Coin Exchanger Rule (in BDT) on InCome call (Don't add multiple rule)",
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('minutes', models.IntegerField(default=0)),
                ('days', models.IntegerField(default=0, verbose_name='Validity Days')),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.AddField(
            model_name='balance',
            name='earn_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
