# Generated by Django 3.2.4 on 2022-10-04 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0008_planpurchased'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='earnminuteexchanger',
            options={'verbose_name_plural': "Earn Minute Exchanger Rule (in BDT) on InCome call (Don't add multiple rule)"},
        ),
        migrations.AlterModelOptions(
            name='planpurchased',
            options={'ordering': ['expired_datetime'], 'verbose_name_plural': 'Plan Purchased'},
        ),
    ]
