# Generated by Django 3.2.4 on 2022-10-04 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('balance', '0009_auto_20221004_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarningHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earn_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Earning Histories',
                'ordering': ['-date'],
            },
        ),
    ]
