# Generated by Django 3.2.4 on 2023-05-04 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0010_earninghistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarnCoinExchanger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_coin_rate', models.DecimalField(decimal_places=2, default=0.2, max_digits=8)),
            ],
        ),
    ]
