# Generated by Django 3.2.4 on 2022-09-20 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('call_histories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callhistory',
            name='caller_user',
        ),
        migrations.AddField(
            model_name='callhistory',
            name='peer_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='call_peer_user', to='accounts.user'),
            preserve_default=False,
        ),
    ]
