# Generated by Django 3.2.4 on 2022-09-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_histories', '0002_auto_20220920_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='callhistory',
            name='call_type',
            field=models.CharField(default='audio', max_length=10),
            preserve_default=False,
        ),
    ]
